name: clone_spotify_sep_2026
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.1
  flutter_svg: ^2.3.0
  form_field_validator: ^1.1.0
  google_nav_bar: ^5.0.7
  readmore: ^3.0.0
  just_audio: ^0.10.6
  image_picker: ^1.2.3
  file_picker: ^11.0.2
  flutter_intl_phone_field: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/musics/
    
  fonts: 
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
